/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-07-04 21:41:33 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost:5432/cobrakinddb -t categories -t markets -s public
 *
 */


export namespace categoriesFields {
    export type id = string;
    export type category_name = string;
    export type category_image = Array<string> | null;

}

export interface categories {
    id: categoriesFields.id;
    category_name: categoriesFields.category_name;
    category_image: categoriesFields.category_image;

}

export namespace marketsFields {
    export type id = string;
    export type category_id = string;
    export type market_name = string;
    export type market_image = Array<string> | null;

}

export interface markets {
    id: marketsFields.id;
    category_id: marketsFields.category_id;
    market_name: marketsFields.market_name;
    market_image: marketsFields.market_image;

}
